-- ============================================================================
-- Evento — initial schema
--
-- Conventions
--   * Primary keys are UUID v4 generated by PostgreSQL (gen_random_uuid, core
--     since PG13 — no pgcrypto extension needed).
--   * All money is stored as an INTEGER NUMBER OF PAISE in BIGINT columns.
--     Floating point currency is a correctness bug waiting to happen; paise
--     also matches what Razorpay expects on the wire.
--   * Every mutable table carries created_at / updated_at, with updated_at
--     maintained by a trigger rather than by application code.
-- ============================================================================

-- ─────────────────────────── helpers ───────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- PostgreSQL marks array_to_string() STABLE rather than IMMUTABLE, because in
-- general an element type's output function may depend on settings. That makes
-- it unusable inside a generated column. For a text[] the result is genuinely
-- deterministic, so this thin wrapper declares the immutability the planner
-- needs to let events.search_vector be a STORED generated column.
CREATE OR REPLACE FUNCTION evento_tags_to_text(tags TEXT[]) RETURNS TEXT
  LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $$ SELECT array_to_string(tags, ' ') $$;

-- ─────────────────────────── enums ─────────────────────────────
CREATE TYPE user_role         AS ENUM ('admin', 'organizer', 'customer');
CREATE TYPE user_status       AS ENUM ('active', 'suspended', 'deleted');
CREATE TYPE organizer_status  AS ENUM ('pending', 'verified', 'rejected', 'suspended');
CREATE TYPE event_status      AS ENUM ('draft', 'pending_review', 'published', 'rejected', 'paused', 'completed', 'cancelled');
CREATE TYPE ticket_kind       AS ENUM ('regular', 'vip', 'early_bird', 'couple_pass', 'group_pass');
CREATE TYPE booking_status    AS ENUM ('pending', 'confirmed', 'cancelled', 'expired', 'refunded', 'partially_refunded');
CREATE TYPE payment_status    AS ENUM ('created', 'pending', 'success', 'failed', 'refunded', 'partially_refunded');
CREATE TYPE payment_method    AS ENUM ('upi', 'credit_card', 'debit_card', 'netbanking', 'wallet', 'mock', 'unknown');
CREATE TYPE refund_status     AS ENUM ('requested', 'approved', 'rejected', 'processed', 'failed');
CREATE TYPE ticket_status     AS ENUM ('valid', 'used', 'cancelled', 'refunded');
CREATE TYPE coupon_type       AS ENUM ('percent', 'flat');
CREATE TYPE notify_status     AS ENUM ('queued', 'sent', 'failed');
CREATE TYPE otp_purpose       AS ENUM ('signup', 'login', 'reset_password', 'verify_email');

-- ─────────────────────────── users ─────────────────────────────
CREATE TABLE users (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name         TEXT        NOT NULL,
  email             TEXT        NOT NULL,
  phone             TEXT,
  password_hash     TEXT,
  role              user_role   NOT NULL DEFAULT 'customer',
  status            user_status NOT NULL DEFAULT 'active',
  avatar_url        TEXT,
  city_id           UUID,
  email_verified_at TIMESTAMPTZ,
  phone_verified_at TIMESTAMPTZ,
  last_login_at     TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_email_format CHECK (position('@' IN email) > 1)
);
-- Emails and phones are matched case/format-insensitively at the app layer;
-- these unique indexes enforce it in the database as the source of truth.
CREATE UNIQUE INDEX users_email_key ON users (lower(email));
CREATE UNIQUE INDEX users_phone_key ON users (phone) WHERE phone IS NOT NULL;
CREATE INDEX users_role_status_idx ON users (role, status);
CREATE INDEX users_created_at_idx ON users (created_at DESC);

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ──────────────────── refresh tokens & OTP ─────────────────────
CREATE TABLE refresh_tokens (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash TEXT        NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  user_agent TEXT,
  ip         TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id) WHERE revoked_at IS NULL;

CREATE TABLE otp_codes (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier  TEXT        NOT NULL,           -- email or phone the code was sent to
  purpose     otp_purpose NOT NULL,
  code_hash   TEXT        NOT NULL,           -- bcrypt hash; the plaintext OTP is never stored
  expires_at  TIMESTAMPTZ NOT NULL,
  attempts    INTEGER     NOT NULL DEFAULT 0,
  consumed_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX otp_codes_lookup_idx ON otp_codes (identifier, purpose, created_at DESC);

-- ─────────────────── reference data: geography ─────────────────
CREATE TABLE cities (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  state         TEXT NOT NULL,
  country       TEXT NOT NULL DEFAULT 'India',
  image_url     TEXT,
  is_popular    BOOLEAN NOT NULL DEFAULT false,
  display_order INTEGER NOT NULL DEFAULT 100,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX cities_popular_idx ON cities (is_popular, display_order);

ALTER TABLE users ADD CONSTRAINT users_city_fk
  FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE SET NULL;

CREATE TABLE categories (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  description   TEXT,
  icon          TEXT,                          -- lucide-react icon name
  color         TEXT NOT NULL DEFAULT '#6366f1',
  display_order INTEGER NOT NULL DEFAULT 100,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ───────────────────────── organizers ──────────────────────────
CREATE TABLE organizers (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  display_name       TEXT NOT NULL,
  slug               TEXT NOT NULL UNIQUE,
  bio                TEXT,
  logo_url           TEXT,
  website            TEXT,
  support_email      TEXT,
  support_phone      TEXT,
  gstin              TEXT,
  pan                TEXT,
  address            TEXT,
  city_id            UUID REFERENCES cities (id) ON DELETE SET NULL,
  status             organizer_status NOT NULL DEFAULT 'pending',
  -- NULL means "inherit the platform-wide commission from settings".
  commission_percent NUMERIC(5, 2) CHECK (commission_percent IS NULL OR (commission_percent >= 0 AND commission_percent <= 100)),
  payout_details     JSONB NOT NULL DEFAULT '{}'::jsonb,
  verified_at        TIMESTAMPTZ,
  verified_by        UUID REFERENCES users (id) ON DELETE SET NULL,
  rejection_reason   TEXT,
  total_events       INTEGER NOT NULL DEFAULT 0,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX organizers_status_idx ON organizers (status);

CREATE TRIGGER organizers_set_updated_at BEFORE UPDATE ON organizers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── venues ────────────────────────────
CREATE TABLE venues (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organizer_id    UUID REFERENCES organizers (id) ON DELETE CASCADE, -- NULL = shared/admin venue
  name            TEXT NOT NULL,
  address_line1   TEXT NOT NULL,
  address_line2   TEXT,
  city_id         UUID NOT NULL REFERENCES cities (id) ON DELETE RESTRICT,
  state           TEXT,
  postal_code     TEXT,
  country         TEXT NOT NULL DEFAULT 'India',
  latitude        NUMERIC(9, 6),
  longitude       NUMERIC(9, 6),
  google_maps_url TEXT,
  capacity        INTEGER CHECK (capacity IS NULL OR capacity > 0),
  landmark        TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX venues_city_idx ON venues (city_id);
CREATE INDEX venues_organizer_idx ON venues (organizer_id);

CREATE TRIGGER venues_set_updated_at BEFORE UPDATE ON venues
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── events ────────────────────────────
CREATE TABLE events (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organizer_id     UUID NOT NULL REFERENCES organizers (id) ON DELETE CASCADE,
  title            TEXT NOT NULL,
  slug             TEXT NOT NULL UNIQUE,
  subtitle         TEXT,
  description      TEXT NOT NULL DEFAULT '',
  category_id      UUID NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
  venue_id         UUID NOT NULL REFERENCES venues (id) ON DELETE RESTRICT,
  city_id          UUID NOT NULL REFERENCES cities (id) ON DELETE RESTRICT,
  banner_url       TEXT,
  thumbnail_url    TEXT,
  gallery          JSONB NOT NULL DEFAULT '[]'::jsonb,
  starts_at        TIMESTAMPTZ NOT NULL,
  ends_at          TIMESTAMPTZ NOT NULL,
  doors_open_at    TIMESTAMPTZ,
  timezone         TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  language         TEXT NOT NULL DEFAULT 'English',
  duration_minutes INTEGER,
  age_limit        INTEGER,
  status           event_status NOT NULL DEFAULT 'draft',
  is_featured      BOOLEAN NOT NULL DEFAULT false,
  is_free          BOOLEAN NOT NULL DEFAULT false,
  terms            TEXT,
  tags             TEXT[] NOT NULL DEFAULT '{}',
  -- Denormalised aggregates, kept in sync by the ticket-type service. They let
  -- the discovery query filter/sort on price without joining ticket_types.
  min_price_paise  BIGINT NOT NULL DEFAULT 0,
  max_price_paise  BIGINT NOT NULL DEFAULT 0,
  total_capacity   INTEGER NOT NULL DEFAULT 0,
  tickets_sold     INTEGER NOT NULL DEFAULT 0,
  view_count       INTEGER NOT NULL DEFAULT 0,
  submitted_at     TIMESTAMPTZ,
  published_at     TIMESTAMPTZ,
  approved_at      TIMESTAMPTZ,
  approved_by      UUID REFERENCES users (id) ON DELETE SET NULL,
  rejection_reason TEXT,
  cancelled_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_vector    tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(subtitle, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(evento_tags_to_text(tags), '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C')
  ) STORED,
  CONSTRAINT events_time_order CHECK (ends_at > starts_at)
);
CREATE INDEX events_search_idx        ON events USING GIN (search_vector);
CREATE INDEX events_discovery_idx     ON events (status, starts_at) WHERE status = 'published';
CREATE INDEX events_city_idx          ON events (city_id, starts_at);
CREATE INDEX events_category_idx      ON events (category_id, starts_at);
CREATE INDEX events_organizer_idx     ON events (organizer_id, created_at DESC);
CREATE INDEX events_featured_idx      ON events (is_featured, starts_at) WHERE is_featured;
CREATE INDEX events_moderation_idx    ON events (status, submitted_at) WHERE status = 'pending_review';
CREATE INDEX events_tags_idx          ON events USING GIN (tags);

CREATE TRIGGER events_set_updated_at BEFORE UPDATE ON events
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ───────────────────────── ticket types ────────────────────────
CREATE TABLE ticket_types (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id         UUID NOT NULL REFERENCES events (id) ON DELETE CASCADE,
  name             TEXT NOT NULL,
  kind             ticket_kind NOT NULL DEFAULT 'regular',
  description      TEXT,
  price_paise      BIGINT  NOT NULL CHECK (price_paise >= 0),
  quantity_total   INTEGER NOT NULL CHECK (quantity_total >= 0),
  -- quantity_sold covers confirmed bookings; quantity_held covers pending ones
  -- whose hold has not yet expired. Availability = total - sold - held.
  quantity_sold    INTEGER NOT NULL DEFAULT 0 CHECK (quantity_sold >= 0),
  quantity_held    INTEGER NOT NULL DEFAULT 0 CHECK (quantity_held >= 0),
  min_per_order    INTEGER NOT NULL DEFAULT 1 CHECK (min_per_order >= 1),
  max_per_order    INTEGER NOT NULL DEFAULT 10 CHECK (max_per_order >= 1),
  seats_per_ticket INTEGER NOT NULL DEFAULT 1 CHECK (seats_per_ticket >= 1),
  sale_starts_at   TIMESTAMPTZ,
  sale_ends_at     TIMESTAMPTZ,
  is_active        BOOLEAN NOT NULL DEFAULT true,
  display_order    INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- The database refuses to oversell, even if application logic regresses.
  CONSTRAINT ticket_types_not_oversold CHECK (quantity_sold + quantity_held <= quantity_total),
  CONSTRAINT ticket_types_order_range  CHECK (max_per_order >= min_per_order),
  CONSTRAINT ticket_types_sale_window  CHECK (sale_ends_at IS NULL OR sale_starts_at IS NULL OR sale_ends_at > sale_starts_at)
);
CREATE INDEX ticket_types_event_idx ON ticket_types (event_id, display_order);

CREATE TRIGGER ticket_types_set_updated_at BEFORE UPDATE ON ticket_types
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── coupons ───────────────────────────
CREATE TABLE coupons (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code                 TEXT NOT NULL,
  description          TEXT,
  type                 coupon_type NOT NULL,
  -- percent → 0-100; flat → discount in paise
  value                NUMERIC(12, 2) NOT NULL CHECK (value > 0),
  max_discount_paise   BIGINT CHECK (max_discount_paise IS NULL OR max_discount_paise > 0),
  min_order_paise      BIGINT NOT NULL DEFAULT 0 CHECK (min_order_paise >= 0),
  usage_limit_total    INTEGER CHECK (usage_limit_total IS NULL OR usage_limit_total > 0),
  usage_limit_per_user INTEGER NOT NULL DEFAULT 1 CHECK (usage_limit_per_user > 0),
  used_count           INTEGER NOT NULL DEFAULT 0,
  valid_from           TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_until          TIMESTAMPTZ,
  event_id             UUID REFERENCES events (id) ON DELETE CASCADE,      -- NULL = all events
  organizer_id         UUID REFERENCES organizers (id) ON DELETE CASCADE,  -- NULL = platform-wide
  created_by           UUID REFERENCES users (id) ON DELETE SET NULL,
  is_active            BOOLEAN NOT NULL DEFAULT true,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT coupons_percent_range CHECK (type <> 'percent' OR value <= 100)
);
CREATE UNIQUE INDEX coupons_code_key ON coupons (upper(code));
CREATE INDEX coupons_active_idx ON coupons (is_active, valid_until);

CREATE TRIGGER coupons_set_updated_at BEFORE UPDATE ON coupons
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── bookings ──────────────────────────
CREATE TABLE bookings (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_code           TEXT NOT NULL UNIQUE,       -- human-facing, e.g. EVT-8FK2M4
  user_id                UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  event_id               UUID NOT NULL REFERENCES events (id) ON DELETE RESTRICT,
  organizer_id           UUID NOT NULL REFERENCES organizers (id) ON DELETE RESTRICT,
  status                 booking_status NOT NULL DEFAULT 'pending',
  quantity               INTEGER NOT NULL CHECK (quantity > 0),
  subtotal_paise         BIGINT NOT NULL DEFAULT 0 CHECK (subtotal_paise >= 0),
  discount_paise         BIGINT NOT NULL DEFAULT 0 CHECK (discount_paise >= 0),
  tax_paise              BIGINT NOT NULL DEFAULT 0 CHECK (tax_paise >= 0),
  convenience_fee_paise  BIGINT NOT NULL DEFAULT 0 CHECK (convenience_fee_paise >= 0),
  total_paise            BIGINT NOT NULL DEFAULT 0 CHECK (total_paise >= 0),
  -- Platform economics, frozen at confirmation time so later rate changes
  -- never rewrite historical revenue reports.
  commission_percent     NUMERIC(5, 2) NOT NULL DEFAULT 0,
  commission_paise       BIGINT NOT NULL DEFAULT 0 CHECK (commission_paise >= 0),
  organizer_payout_paise BIGINT NOT NULL DEFAULT 0 CHECK (organizer_payout_paise >= 0),
  refunded_paise         BIGINT NOT NULL DEFAULT 0 CHECK (refunded_paise >= 0),
  coupon_id              UUID REFERENCES coupons (id) ON DELETE SET NULL,
  coupon_code            TEXT,
  customer_name          TEXT NOT NULL,
  customer_email         TEXT NOT NULL,
  customer_phone         TEXT NOT NULL,
  notes                  TEXT,
  hold_expires_at        TIMESTAMPTZ,
  confirmed_at           TIMESTAMPTZ,
  cancelled_at           TIMESTAMPTZ,
  cancellation_reason    TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX bookings_user_idx      ON bookings (user_id, created_at DESC);
CREATE INDEX bookings_event_idx     ON bookings (event_id, status);
CREATE INDEX bookings_organizer_idx ON bookings (organizer_id, created_at DESC);
CREATE INDEX bookings_status_idx    ON bookings (status, created_at DESC);
-- Drives the sweeper that releases inventory from abandoned checkouts.
CREATE INDEX bookings_expiry_idx    ON bookings (hold_expires_at) WHERE status = 'pending';

CREATE TRIGGER bookings_set_updated_at BEFORE UPDATE ON bookings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE booking_items (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id       UUID NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
  ticket_type_id   UUID NOT NULL REFERENCES ticket_types (id) ON DELETE RESTRICT,
  -- Name and price are snapshotted: an organizer renaming or repricing a tier
  -- must not retroactively change what a customer already paid for.
  ticket_type_name TEXT NOT NULL,
  unit_price_paise BIGINT NOT NULL CHECK (unit_price_paise >= 0),
  quantity         INTEGER NOT NULL CHECK (quantity > 0),
  subtotal_paise   BIGINT NOT NULL CHECK (subtotal_paise >= 0),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (booking_id, ticket_type_id)
);
CREATE INDEX booking_items_booking_idx ON booking_items (booking_id);

-- ──────────────────────── issued tickets ───────────────────────
CREATE TABLE tickets (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_code     TEXT NOT NULL UNIQUE,      -- printed on the ticket, embedded in the QR
  booking_id      UUID NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
  booking_item_id UUID NOT NULL REFERENCES booking_items (id) ON DELETE CASCADE,
  event_id        UUID NOT NULL REFERENCES events (id) ON DELETE CASCADE,
  ticket_type_id  UUID NOT NULL REFERENCES ticket_types (id) ON DELETE RESTRICT,
  attendee_name   TEXT NOT NULL,
  seat_label      TEXT,
  status          ticket_status NOT NULL DEFAULT 'valid',
  -- HMAC of the ticket code; the QR carries code + signature so a scanner can
  -- reject forgeries before touching the database.
  qr_signature    TEXT NOT NULL,
  checked_in_at   TIMESTAMPTZ,
  checked_in_by   UUID REFERENCES users (id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX tickets_booking_idx ON tickets (booking_id);
CREATE INDEX tickets_event_idx   ON tickets (event_id, status);

-- ─────────────────────────── payments ──────────────────────────
CREATE TABLE payments (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id          UUID NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
  provider            TEXT NOT NULL DEFAULT 'razorpay',
  provider_order_id   TEXT,
  provider_payment_id TEXT,
  provider_signature  TEXT,
  amount_paise        BIGINT NOT NULL CHECK (amount_paise >= 0),
  currency            TEXT NOT NULL DEFAULT 'INR',
  status              payment_status NOT NULL DEFAULT 'created',
  method              payment_method NOT NULL DEFAULT 'unknown',
  error_code          TEXT,
  error_description   TEXT,
  raw_response        JSONB NOT NULL DEFAULT '{}'::jsonb,
  captured_at         TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX payments_booking_idx ON payments (booking_id, created_at DESC);
CREATE UNIQUE INDEX payments_order_key   ON payments (provider_order_id)   WHERE provider_order_id IS NOT NULL;
CREATE UNIQUE INDEX payments_payment_key ON payments (provider_payment_id) WHERE provider_payment_id IS NOT NULL;

CREATE TRIGGER payments_set_updated_at BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Webhook ledger. The UNIQUE constraint on provider_event_id is what makes
-- webhook processing idempotent under provider retries.
CREATE TABLE payment_events (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider          TEXT NOT NULL DEFAULT 'razorpay',
  provider_event_id TEXT NOT NULL,
  event_type        TEXT NOT NULL,
  payment_id        UUID REFERENCES payments (id) ON DELETE SET NULL,
  payload           JSONB NOT NULL,
  processed_at      TIMESTAMPTZ,
  error             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_event_id)
);

-- ─────────────────────────── refunds ───────────────────────────
CREATE TABLE refunds (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id         UUID NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
  payment_id         UUID REFERENCES payments (id) ON DELETE SET NULL,
  requested_by       UUID REFERENCES users (id) ON DELETE SET NULL,
  amount_paise       BIGINT NOT NULL CHECK (amount_paise > 0),
  reason             TEXT NOT NULL,
  status             refund_status NOT NULL DEFAULT 'requested',
  provider_refund_id TEXT,
  admin_note         TEXT,
  reviewed_by        UUID REFERENCES users (id) ON DELETE SET NULL,
  reviewed_at        TIMESTAMPTZ,
  processed_at       TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX refunds_status_idx  ON refunds (status, created_at DESC);
CREATE INDEX refunds_booking_idx ON refunds (booking_id);

CREATE TRIGGER refunds_set_updated_at BEFORE UPDATE ON refunds
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE coupon_redemptions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id      UUID NOT NULL REFERENCES coupons (id) ON DELETE CASCADE,
  booking_id     UUID NOT NULL UNIQUE REFERENCES bookings (id) ON DELETE CASCADE,
  user_id        UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  discount_paise BIGINT NOT NULL CHECK (discount_paise >= 0),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX coupon_redemptions_user_idx ON coupon_redemptions (coupon_id, user_id);

-- ───────────────── platform settings & observability ───────────
CREATE TABLE settings (
  key         TEXT PRIMARY KEY,
  value       JSONB NOT NULL,
  description TEXT,
  updated_by  UUID REFERENCES users (id) ON DELETE SET NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID REFERENCES users (id) ON DELETE SET NULL,
  booking_id UUID REFERENCES bookings (id) ON DELETE SET NULL,
  event_id   UUID REFERENCES events (id) ON DELETE SET NULL,
  channel    TEXT NOT NULL DEFAULT 'email',
  template   TEXT NOT NULL,
  to_address TEXT NOT NULL,
  subject    TEXT NOT NULL,
  payload    JSONB NOT NULL DEFAULT '{}'::jsonb,
  status     notify_status NOT NULL DEFAULT 'queued',
  error      TEXT,
  sent_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX notifications_user_idx   ON notifications (user_id, created_at DESC);
CREATE INDEX notifications_status_idx ON notifications (status, created_at);

CREATE TABLE audit_logs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id    UUID REFERENCES users (id) ON DELETE SET NULL,
  actor_role  user_role,
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   TEXT,
  metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip          TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_entity_idx ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_logs_actor_idx  ON audit_logs (actor_id, created_at DESC);
